modLoader="javafml" #mandatory
loaderVersion="[35,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"

[[mods]] #mandatory
modId="orebushes" #mandatory
version="1.0.0" #mandatory
displayName="Ore Bushes" #mandatory
authors="thenatekirby" #optional
description='''
Grow your ores.
'''

[[dependencies.orebushes]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[35,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.orebushes]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.orebushes]]
    modId="babel"
    mandatory=true
    versionRange="[1.0.0,2.0.0)"
    ordering="AFTER"
    side="BOTH"
